[WiP] [MTSRE-528] serviceMonitor for AddonCR.
mt-sre/managed-tenants-cli pull request #158
Opened 2022-05-03 18:58 UTC by sugarraysam

# py-mtcli

## Description

Feature parity with the addon-operator.

Depends on https://github.com/openshift/addon-operator/pull/186

2022-05-04 13:48 UTC, sandhyadalavi commented on tests/sss/test_federated_metrics.py
> +        "namespace": data.draw(custom_strategies.namespace()),
can we add matchlabels and matchnames here?

2022-05-04 13:53 UTC, apahim requested changes
Can we remove the AddonCR from the SelectorSyncSet instead? It's not used anywhere, it's just causing confusion, and the feature parity work should happen here:

https://github.com/openshift/addon-operator/blob/main/internal/controllers/addon/phase_ensure_monitoring_federation.go

2022-05-05 08:01 UTC, apahim commented
I see you hve it here: https://github.com/openshift/addon-operator/pull/186/files

So, yeah, it all good, I believe. Unless OCM needs to pass some parameter through, as it's OCM who creates the Addon CR, not this SSS.

2022-05-06 13:54 UTC, sugarraysam commented
@apahim let me close this PR then and create a new one for the removal of the Addon CR.

2022-05-06 13:54 UTC, closed without merging