Add optional `addons` property to mtbundles schema
mt-sre/managed-tenants-cli pull request #81
Opened 2022-01-20 18:29 UTC by MikeEdgar

Proposal to add optional `addons` property to mtbundles schema

2022-01-24 15:18 UTC, sugarraysam requested changes

2022-01-25 11:44 UTC, MikeEdgar commented on managedtenants/schemas/mtbundles.schema.yaml
> +  addons:
Done

2022-02-08 14:16 UTC, MikeEdgar commented
This PR should be current now, but I can't see the build job to check on the failure.

2022-02-08 18:44 UTC, Ajpantuso commented
/retest

2022-02-08 18:48 UTC, Ajpantuso commented
> This PR should be current now, but I can't see the build job to check on the failure.

It was a [dependency issue](https://github.com/mt-sre/managed-tenants-cli/pull/92). This should be pass CI now.

2022-02-09 13:39 UTC, Ajpantuso commented on managedtenants/schemas/mtbundles.schema.yaml
> +  addons:
@sugarraysam I don't think we need a full deprecation flow, but I'd prefer we order the changes like:
1. Only add the new `addons` property with this PR
2. Utilize just the refactors for `ci.py` from !245 so either `environments` or `addons` is accepted with `addons` preferred if available.
3. Migrate any necessary `config.yaml`s
4. Drop the `environment` property and branching code path in `ci.py`

Then feature is delivered at step 2 and `config.yaml` migrations are no longer a blocker, but just a cleanup task.

2022-02-10 12:42 UTC, Ajpantuso commented on managedtenants/schemas/mtbundles.schema.yaml
> +  addons:
Ah, then let's just merge this.

2022-02-11 13:20 UTC, sugarraysam approved these changes

2022-02-11 13:34 UTC, merged