OCM: Add attributes necessary for STS addons
mt-sre/managed-tenants-cli pull request #89
Opened 2022-02-04 20:57 UTC by vkareh

When installing an addon that needs access to AWS resources on an STS
cluster, the addon needs to announce which service account to use for
generating the token and the list of policy permissions required.

This will allow ROSA to guide the user through the role/policy creation
process, and allow OCM to validate that the authentication works when
the user supplies the resulting IAM role ARN.

* https://issues.redhat.com/browse/SDA-5367
* https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/3783
* https://github.com/openshift-online/ocm-api-model/pull/484

2022-02-04 20:58 UTC, vkareh commented
/cc @apahim @ciaranRoche @pvasant

2022-02-07 08:54 UTC, ciaranRoche commented
lgtm

2022-02-08 18:32 UTC, Ajpantuso commented
/retest

2022-02-09 14:08 UTC, apahim commented
lgtm, please add tenants docs to https://gitlab.cee.redhat.com/service/managed-tenants/-/tree/main/docs/ocm

2022-02-17 16:59 UTC, sugarraysam requested changes
Please update the `description:` field and regenerate Markdown. After I believe we're good for merging.

2022-02-17 16:59 UTC, sugarraysam commented on managedtenants/schemas/metadata.schema.yaml
> +    type: string
```yaml
serviceAccount:
  type: string
  description: "Name of the service account created by the addon operator to authenticate to the API."
```

2022-02-17 16:59 UTC, sugarraysam commented on managedtenants/schemas/metadata.schema.yaml
> +  policyPermissions:
```yaml
policyPermissions:
  type: array
  description: "List of permissions in an IAM policy that are required by the addon operator."
```

2022-02-22 20:40 UTC, vkareh commented
@sugarraysam - fixed

2022-02-23 14:26 UTC, sugarraysam commented
lgtm

2022-02-23 14:43 UTC, sugarraysam approved these changes

2022-02-23 14:43 UTC, merged